
# Build matrix
language: node_js
matrix:
  include:

    # Run linter once

    - node_js: '8'
      env: LINT=true

    # Run tests with varying Node.js versions

    - node_js: '4'
      env: NODE=4

    - node_js: '6'
      env: NODE=6

    - node_js: '8'
      env: NODE=8

# Build script
script:
  - 'if [ $LINT ]; then make verify; fi'
  - 'if [ $NODE ]; then make test; fi'
